name: Scheduled Message

on:
  schedule:
    # Runs every day at 12:00 UTC
    - cron: '0 12 * * *'

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print to stdout
        run: echo "Hello! This is a scheduled message."