name: Run TestNG Tests with Allure Reporting

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'test suite path'
        default: 'src/test/resources/suites/all-test.xml'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Run TestNG Tests
        run: ./mvnw test -Dsurefire.suiteXmlFiles=${{ github.event.inputs.suite }}

      - name: Save Allure Report as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
